# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7260e81ee9a264f9d84847ee27d9d505a8f3945f058c34bab5fe890c0ec52849e1042baa602a53fcedb68de93be61c3f46e752810dae16ae7224fca06ab336f

test:
  secret_key_base: bffcefafa4b3f68c9f0dfb470f8450f7c72a01a20b75f7f0b96560937e8631d1d356ff7b60ce54d788d3846104ab977a3d4960f9e133b178fa25240cb8174908

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
